
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mandu1234567/kubernetes.git
    targetRevision: HEAD
    path: day-4-apllication-set/app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
